### PR TITLE
Upgrade Scribe

### PR DESCRIPTION
**Pull request by rogerhu**
- Downgrade back to 1.1.0 (since Bintray doesn't allow 1.1.1 upgrade after 180+ days)
- Upgrade Scribe library to use Gradle version
     - Support mostly confined to OAuth1.0 (OAuth2 has refresh tokens that need recording)

### CODE REVIEW

**Comment by rogerhu** [comment]
Got this to work with android rest client.  No more custom Scribe jar!

**Comment by nesquena** [comment]
Woah nice! Is this possible now because it changes to the way scribe is designed now? It used to be that there was no way to use scribe and send requests with android-async

**Comment by rogerhu** [comment]
The wrapper around scribe is still needed.  Later versions of Scribe make a clearer distinction between Oauth1 and Oauth2 though and we are simply no longer using a custom JAR.  i Iintend to add Oauth2 support but at least got stuff working with the Twitter API.

**Comment by nesquena** [comment]
Awesome, so nice to get rid of that super old fork of scribe!

**Pull request merged**
