### PR TITLE
Bintray

### PR DESCRIPTION
**Pull request by rogerhu**
@nesquena

### CODE REVIEW

**Comment by rogerhu** [comment]
This stuff is also ready to go.

**Comment by nesquena** [comment]
@rogerhu any further steps we need to take here now that this is merged?

**Comment by rogerhu** [comment]
Retested by redoing Twitter setup and everything works great for Async Http Client v1.4.9 now.

Also please join BinTray and I can add you to a member of the codepath org.  Instructions for pushing BinTray updates located here: http://guides.codepath.com/android/Building-your-own-Android-library#setting-up-through-jcenter

**Comment by nesquena** [comment]
> Retested by redoing Twitter setup and everything works great for Async Http Client v1.4.9 now.

Great! Thanks for getting this going, much cleaner than having to use JARS and the old Async HTTP version!

> Also please join BinTray and I can add you to a member of the codepath org. Instructions for pushing BinTray updates located here: http://guides.codepath.com/android/Building-your-own-Android-library#setting-up-through-jcenter

@rogerhu can you add me to the codepath org. (email: nathan AT thecodepath)

**Pull request merged**
